### ISSUE TITLE
Option for AlmaLinux?

### ISSUE THREAD

**Issue by vwbusguy** [ericcurtin/asahi-centosstream-builder#1]
Since AlmaLinux is close to CentOS Stream and now build from Stream sources, would it be possible to use this to install AlmaLinux?  If it's helpful, I already have some boxes successfully running Fedora 38 with leifleddy's script and so far, they've been working perfectly for our use cases.  We're using AlmaLinux9 now for ARM Jenkins build nodes and it would be great to add these boxes into the mix running the same OS across the builders. 

If it's not in your scope at the moment, I might be able to help out, with the caveat that while I'm very comfortable with hacking Linux, Mac hardware is not my area of expertise.

**Comment by ericcurtin** [comment]
So this version:

https://fedora-asahi-remix.org/

are actually the most official Fedora Asahi Remix images which Leif also helped create.

Technically no CentOS Stream-based distro can run Asahi as the kernel is too old. CentOS Stream 10 kernels (when it's released) would if you rebuilt them with 16k and turned a few options on.

I think Fedora with CentOS Stream/AlmaLinux vms/containers would likely be the best way for you to be honest. It's less maintenance for all involved.

Containers > vms also because KVM treats big.LITTLE kinda funny tbh. So I'd recommend podman or distrobox maybe if it fits your use case. On Fedora host.

**Comment by ericcurtin** [comment]
The goal of the Asahi project in general is to upstream as much as possible so that standard .iso's etc. just work. But it's a longer term thing for now.

**Comment by vwbusguy** [comment]
Sure.  I'm guessing that's why Leifleddy's Fedora stuff works, since Fedora runs ever-newer kernels.  Getting it to work on EL9 compatible kernels for CentOS Stream (and potentially/hopefully AlmaLinux9 from there?) is what I imagine is the more difficult task of this particular repo, right?

**Comment by vwbusguy** [comment]
From a quick look, most of what would be needed to support AlmaLinux here would be a matter of the mkosi conf and the repos.  I think I could probably make this work by adding separate repo and mkosi files to support AlmaLinux and drawing those in instead of the CentOS ones in your script by an runtime command, ie something like `./build.sh --target-os=AlmaLinux`.

**Comment by ericcurtin** [comment]
Well I got it working at one point, by using a newer kernel with CentOS Stream 9, but I stopped maintaining, because I thought, what's the point, it's not a CentOS Steam 9 kernel and I can get CentOS Steam 9 userspace with a container. And if I really really need a CentOS Stream 9-like kernel on ARM, I can use a KVM vm, which I do everyday for my CentOS Automotive Stream distribution based work...

But I would recommend podman/distrobox if you just need a EL9 userspace.

And hey in fact you could actually use a RHEL9 container or vm for free if you wanted, up to 16 nodes for the VM use case.

But it's worth revisiting in the EL10 distros possibly as a community thing, especially for the headless use case.

**Comment by vwbusguy** [comment]
I was thinking that it might still be possible using a newer [ELRepo](https://elrepo.org/linux/kernel/el9/x86_64/) or possibly Hyperspace SIG kernel (though this currently seems probably too old).

**Comment by ericcurtin** [comment]
You're free to give things a shot. Fedora will be the best supported for now.

Next on my list to help out where I can will probably be an immutable ostree-variant like Silverblue. Unblocking the effort where I can.

**Comment by vwbusguy** [comment]
One thing I don't grok, and I'm sorry if this is obvious, but when you got it to work, how were the Asahi Linux kernel patches applied to the CS kernel?  

Edit:  It looks like you are referencing a repo that doesn't seem to exist anymore - https://github.com/ericcurtin/asahi-centosstream-builder/blob/main/mkosi.skeleton/etc/yum.repos.d/asahi-linux.repo .  Would you still happen to have the sources/spec's in a repo somewhere I could reference?

**Comment by ericcurtin** [comment]
Look for the patches by me or Neal Gompa

https://gitlab.com/fedora-asahi/kernel-asahi

**Comment by vwbusguy** [comment]
Any chance the srpms are still available for the repo that used to exist for this project?

**Comment by ericcurtin** [comment]
Even if I could find them I wouldn't recommend they haven't been touched in almost I year... I'd recommend examining Fedora Asahi Remix's included .src.rpms

**Comment by vwbusguy** [comment]
Thanks for your responses here.  Between this and https://github.com/leifliddy/asahi-rocky-builder, I think I'll have what I need to get started.  Many thanks!
